apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: topics.kafka.mycompany.io
spec:
  scope: Namespaced
  group: kafka.mycompany.io
  names:
    kind: KafkaTopic
    plural: topics
    singular: topic
    shortNames:
      - kt
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                kafkaServer:
                  type: string
                topicName:
                  type: string
                topicProperties:
                  type: array
                  items:
                    type: object
                    properties:
                      replicationFactor:
                        type: integer
                      numPartitions:
                        type: integer
